[project]
name = "tbh"
version = "0.1.0"
description = "Add a short description here"
authors = [{name = "Romain Ragonnet", email = "romain.ragonnet@monash.edu"}]
requires-python = ">= 3.10"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"